### ISSUE TITLE
EPIC: Test the framework

### ISSUE THREAD

**Issue by laurentsenta** [ipfs/gateway-conformance#119]
We already have a few unit-tests in the framework, but coverage is low

- [ ] measure test coverage
- [ ] look into cassettes(related: https://github.com/vcr/vcr)
- [ ] look into the randomizer proxy (https://github.com/ipfs/gateway-conformance/pull/29)
