### ISSUE TITLE
EPIC: Specs Integration and Status Reporting (Step 1)

### ISSUE THREAD

**Issue by laurentsenta** [ipfs/gateway-conformance#120]
TBD

ETA: 2023-12-01

```[tasklist]
- [ ] https://github.com/ipfs/gateway-conformance/issues/104
- [ ] https://github.com/ipfs/public-gateway-checker/issues/442
- [ ] Specs Integration (TBD)
- [ ] Make the [dashboard discussion document](https://www.notion.so/pl-strflt/Gateway-Conformance-Dashboards-10490048436e456d99d40016586a6937?d=b05e65b338af45f0b62cdb1069c9a9b7) public
```
