### ISSUE TITLE
IPFS Gateway Conformance 2023-2024 Roadmap

### ISSUE THREAD

**Issue by laurentsenta** [ipfs/gateway-conformance#122]
### Gateway Conformance
- [ ] https://github.com/ipfs/gateway-conformance/issues/120
- [ ] https://github.com/ipfs/gateway-conformance/issues/119

### Test Coverage
- [ ] https://github.com/ipfs/gateway-conformance/issues/121

[Starmap Link](https://starmap.site/roadmap/github.com/ipfs/gateway-conformance/issues/122#view=simple)
