### ISSUE TITLE
Version 1.0 - Tasks

### ISSUE THREAD

**Issue by laurentsenta** [ipfs/gateway-conformance#8]
(wip)

- [x] Use
  - [x] Use the action in Kubo CI https://github.com/ipfs/kubo/pull/9780
  - [x] use in boxo https://github.com/ipfs/boxo/pull/246
  - [x] use in bifrost-gateway CIs https://github.com/ipfs/bifrost-gateway/issues/63
  - [x] Implement a "gateway conformance dashboard" in grafana - track conformance testing for every client repo
    - [WIP](https://protocollabs.grafana.net/d/hVIdANYVz/audit-ipdx-statuses?orgId=1)
  - [x] document the actions in the README.md
  - [x] Validate (and improve if needed) the local dev usage - currently we documented large, convoluted, docker run commands - https://github.com/ipfs/gateway-conformance/pull/102
- [x] Port all the tests
   - [x] Start With https://github.com/ipfs/gateway-conformance/issues/3
   - [x] port gateway subdomains tests #9 
      - [x] Look into DNS resolver (https://github.com/ipfs/gateway-conformance/pull/9)
   - [x] port IPNS tests
      - [x] Look into IPNS record importers #10
      - [x] Look into DNS Link "importers" #22
   - [x] #93 
   - [x] #26
- [x] Implement the entry point as a binary that can take complex arguments (like optional gateway, etc)
  - [x] add an option to enable failing / passing tests (for our CI) - maybe?
  - [x] add an option for optional test subdomains (https://github.com/ipfs/gateway-conformance/pull/14)
- [x] Project Maintenance
  - [x] Decide: Move to unified CI? - https://github.com/ipfs/gateway-conformance/pull/103#issuecomment-1617447669
  - [x] Move to unified CI - https://github.com/protocol/.github/pull/535 - https://github.com/ipfs/gateway-conformance/pull/107
- [x] Implement tests
  - [x] Test the checkers and reporters, especially `Shell` Check.
  - [x] Test the frameworks (unit-tests)
  - [x] Test the test suite with multiple targets (especially subdomains, with https://dweb.link/ for example) https://github.com/ipfs/gateway-conformance/issues/104
- [x] update specs support
  - [x] https://github.com/ipfs/gateway-conformance/pull/15#discussion_r1141927574

## Pre-release

- [-] add a regression test for non-inlined dnslinks on localhost tests
    - See https://github.com/ipfs/gateway-conformance/pull/53
    - https://github.com/ipfs/gateway-conformance/issues/118
- [x] Update the way we work with ipns records 
    - See https://github.com/ipfs/gateway-conformance/pull/53#discussion_r1227359428
    - https://github.com/ipfs/gateway-conformance/commit/150a3df54e34af12555ec9701835aa5a5ae317d2

## Follow-Ups

- https://github.com/ipfs/gateway-conformance/issues/119
- https://github.com/ipfs/gateway-conformance/issues/120

**Comment by laurentsenta** [comment]
ipfs things: 14th of April, plan to come.

**Comment by laurentsenta** [comment]
note from Lidel on testing hamt: https://github.com/ipfs/kubo/pull/9681#pullrequestreview-1353785481

**Comment by laurentsenta** [comment]
ipfs things workshop relates notes (wip): https://github.com/ipfs/gateway-conformance/blob/workshop-ipfsthing23/docs/workshop-ipfsthing23.md

**Comment by laurentsenta** [comment]
(moved cassette testing to a follow-up task, we'll investigate later, related: https://github.com/ipfs/gateway-conformance/pull/29)

**Comment by laurentsenta** [comment]
Closing this 🥳 

cc @galargh
